import '../styles/globals.css'
import Head from 'next/head'
import Header from '../components/layout/Header'
import { AuthContextProvider } from '../context/AuthContext'

export default function App({ Component, pageProps }) {
    return (
        <AuthContextProvider>
            <Head>
                <title>Vac List</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <Component {...pageProps} />
        </AuthContextProvider>
    )

    // return (
    //     <AuthContextProvider>
    //         {noAuthRequired.includes(router.pathname) ? (
    //             <>
    //                 <Component {...pageProps} />
    //             </>
    //         ) : (
    //             <ProtectedRoute>
    //                 <Nav />
    //                 <Component {...pageProps} />
    //                 {width <= 768 && <MobileNav />}
    //             </ProtectedRoute>
    //         )}
    //     </AuthContextProvider>
    // )
}
